#current
# probably could just have a bootstrap container or something
bootstrap_url: http://10.0.5.65:8000
cluster_name: DCOS
exhibitor_storage_backend: zookeeper
# this never seems to work? at least I don't see anything under /dcos-dad
exhibitor_zk_hosts: 10.0.5.65:2181
exhibitor_zk_path: /dcos-dad
master_discovery: master_http_loadbalancer
# get cryptokey from /navstar/lashup/key
exhibitor_address: dcos-dad-master.marathon.containerip.dcos.4s94a3xtetxwedpkfoqrulwn399mud6exteg3tmj8iai73tzsruy.dcos.directory
num_masters: 3
# this could probably just be upstream
resolvers:
 - 10.0.5.65
# whos got time for time anyway
check_time: false
customer_key: 12345-12346-12356-12456-13456-234561
#gotta make sure to put overlay on a different subnet than the root DC/OS
dcos_overlay_network:
      vtep_subnet: 44.128.0.0/20
      vtep_mac_oui: 70:B3:D5:00:00:00
      overlays:
        - name: dcos
          subnet: 192.168.0.0/16
          prefix: 24
